- id: check-links
  name: Check links in markdown files
  entry: check-links
  language: python
  language_version: python3

- id: markdown-toc
  name: Update markdown tables of contents
  entry: markdown-toc
  language: python
  language_version: python3
