from typing import Dict, List

mapping_nature_code: Dict[str, List[str]] = {
    "COFFRET": [
        "peau",
        "coffret",
        "parfum",
        "crème",
        "sans",
        "cheveux",
        "produits",
        "tout",
    ],
    "CREM JOUR": [
        "peau",
        "crème",
        "plus",
        "soin",
        "visage",
        "peaux",
        "cette",
        "texture",
        "jour",
    ],
    "EAUPARFUM": [
        "parfum",
        "flacon",
        "eau",
        "notes",
        "rose",
        "dun",
        "dune",
        "plus",
        "fragrance",
        "cette",
    ],
    "EAUTOIL": [
        "parfum",
        "toilette",
        "notes",
        "flacon",
        "eau",
        "dun",
        "leau",
        "fragrance",
        "homme",
        "dune",
    ],
    "MASCARAS": [
        "cils",
        "mascara",
        "volume",
        "plus",
        "brosse",
        "formule",
        "sans",
        "regard",
        "effet",
        "intense",
    ],
    "NETTOYANT": [
        "peau",
        "nettoyant",
        "sans",
        "impuretés",
        "dorigine",
        "plus",
        "visage",
        "peaux",
        "tout",
        "mousse",
    ],
    "PALETYEUX": [
        "palette",
        "teintes",
        "paupières",
        "fards",
        "cette",
        "couleurs",
        "mat",
        "looks",
        "plus",
        "yeux",
    ],
    "RAL": [
        "lèvres",
        "rouge",
        "couleur",
        "formule",
        "sans",
        "fini",
        "plus",
        "tenue",
        "mat",
        "teintes",
    ],
    "SERUM": [
        "peau",
        "sérum",
        "plus",
        "dorigine",
        "sans",
        "teint",
        "cheveux",
        "formule",
        "visage",
        "naturelle",
    ],
    "SHAMPOINGS": [
        "cheveux",
        "shampoing",
        "sans",
        "plus",
        "cuir",
        "chevelu",
        "shampooing",
        "dorigine",
        "formule",
        "douceur",
    ],
}

mapping_target_code = {
    "FEMME": [
        "peau",
        "plus",
        "sans",
        "formule",
        "lèvres",
        "cils",
        "1",
        "parfum",
        "cheveux",
        "origine",
        "cette",
        "eau",
        "rouge",
        "tout",
        "soin",
        "ingrédients",
        "crème",
        "texture",
        "mascara",
        "volume",
    ],
    "HOMME": [
        "parfum",
        "eau",
        "homme",
        "toilette",
        "notes",
        "flacon",
        "peau",
        "plus",
        "bois",
        "fraîcheur",
        "fragrance",
        "cette",
        "intense",
        "accord",
        "boisé",
        "hommes",
        "sillage",
    ],
}
